#ifndef __PERMISSOES__DE__USUARIO__
#define __PERMISSOES__DE__USUARIO__


#define PERMISSAO_NULA 0

#define PERMISSAO_OBTER_QUANTIDADE_DE_HABITANTES_NA_CIDADE 1


#define PERMISSAO_GLOBAL 9999999

#endif